### ISSUE TITLE
How to bypass Cloudflare "Checking your browser before accessing "?

### ISSUE THREAD

**Issue by RyouMon** [RyouMon/FavoritesCrawler#25]
run command: "favors crawl nhentai"，got 503 responses.

**Comment by RyouMon** [comment]
1. Add your IP and User-Agent to cloudflare whitelist, just open nhentai with browser to do this.
![image](https://user-images.githubusercontent.com/42371625/182615125-ae094489-2e0f-462e-b4a2-b865500b99ec.png)

3. Set UserAgent() in ~/.favorites_crawler/config.yml.
```yaml
lemon:
  ...
nhentai:
  USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/1....  # copy from your browser
pixiv:
   ...
yandere:
   ...
```

3. Make sure you have copied cookie file to ~/.favorites_crawler.
![image](https://user-images.githubusercontent.com/42371625/182613491-59a876b9-88f3-431a-8d9e-0991978a03ca.png)

4. Send request with cookies. (I will fix this bug.)
